name: Create Dev Release

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: "stable"
            - run: flutter config --enable-windows-desktop --disable-telemetry
            - run: flutter clean
            - run: flutter build windows --release

            - name: Upload Windows Build Artifact
              id: upload_win_artifact
              uses: actions/upload-artifact@v3
              with:
                name: windows-build-artifact
                path: .\build\
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                channel: "stable"
            - run: |
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev
            - run: flutter config --enable-linux-desktop --disable-telemetry
            - run: flutter clean
            - run: flutter build linux --release

            - name: Upload Linux Build Artifact
              id: upload_linux_artifact
              uses: actions/upload-artifact@v3
              with:
                name: linux-build-artifact
                path: ./build/
    do-release:
        runs-on: ubuntu-latest
        needs: [build-linux, build-windows]
        steps:
            - name: Download Build Artifacts
              id: retrieve_artifacts
              uses: actions/download-artifact@v3

            - name: Compress Build Outputs & Upload Release
              id: compress_outputs
              run: |
                sudo apt install zip tar
                cd /home/runner/work/sprix-ytdlp-frontend/sprix-ytdlp-frontend/
                zip -r ./windows.zip ./windows-build-artifact/build/windows/runner/Release
                tar -zcf ./linux.tar.gz ./linux-build-artifact/linux/x64/release/

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                draft: true
                prerelease: true
                automatic_release_tag: "latest"
                title: "Latest Development Build"
                files: |
                    windows.zip
                    linux.tar.gz